version: "3"
services:
  postgres:
    image: postgres:15
    mem_reservation: 1G
    environment:
      POSTGRES_USER: turreta
      POSTGRES_PASSWORD: a1128f69-e6f7-4e93-a2df-3d4db6030abc
    ports:
      - "5442:5432"
    networks:
      - turreta_network
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: karl.sangabriel@gmail.com
      PGADMIN_DEFAULT_PASSWORD: a1128f69-e6f7-4e93-a2df-3d4db6030abc
    ports:
      - "8889:80"
    networks:
      - turreta_network
networks:
  turreta_network:
    driver: bridge

volumes:
  db-data: