version: "3"
services:
  postgres:
    image: postgres
    mem_reservation: 1G
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    ports:
      - "5433:5432"
    networks:
      - richie_network
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "8089:80"
    networks:
      - richie_network
    restart: unless-stopped

networks:
  richie_network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
