server:
  port: 8085

spring:
  application:
    name: api-gateway
  datasource:
    username: ${POSTGRES_USER}
    url: ${POSTGRES_URL_FRAUD}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  zipkin:
    base-url: ${ZIPKIN_URL}
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
