server:
  port: 8060

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: ${ZIPKIN_URL}
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
