server:
  port: 8061

spring:
  application:
    name: customer
  datasource:
    username: ${POSTGRES_USER}
    url: ${POSTGRES_URL}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  zipkin:
    base-url: ${ZIPKIN_URL}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}

