server:
  port: 8063

spring:
  application:
    name: notification
  datasource:
    username: ${POSTGRES_USER}
    url: ${POSTGRES_URL_NOTIFICATION}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  zipkin:
    base-url: ${ZIPKIN_URL}
  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
    fetch-registry: true
    register-with-eureka: true
#  instance:
#    hostname: localhost

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key