server:
  port: 8062

spring:
  application:
    name: fraud
  datasource:
    username: ${POSTGRES_USER}
    url: ${POSTGRES_URL_FRAUD}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  zipkin:
    base-url: ${ZIPKIN_URL}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
    fetch-registry: true
    register-with-eureka: true
#  instance:
#    hostname: localhost

